### ISSUE TITLE
BNO080-general.c does not work on my RPi 3B+

### ISSUE THREAD

**Issue by tbrych** [BBUK/Bell-Boy#1]
Hey @BBUK!

I downloaded your code and copied it on my RPi 3B+, after that I installed the BCM2835 lib and compiled your code. 
When executing, I get the error "Unsolicited packet not received\n". What does does it mean, that the unsolicited packet wasn't received. This error-message doesn't make any sense to me.
What can I do against it?

The pins connected on the BNO080 are:
PS1 ->   3.3V
GND ->   GND
VDD ->   3.3V
SCK ->   BCM11
SO  ->   BCM9
SI  ->   BCM10
CS  ->   BCM8
WAK ->   BCM25
RST ->   BCM24
INT ->   BCM23

Thank you!
tbrych

**Comment by BBUK** [comment]
Hi tbrych.
On reset the BNO080 (should) send a reset packet followed by a long (over 250 byte) unsolicited capability advertisement packet.  The code is complaining that it is not seeing the unsolicited packet.  The wiring looks OK,  What BNO080 board are you using?
BBUK

**Comment by tbrych** [comment]
We use a Sparkfun BNO080 (https://www.sparkfun.com/products/14686)

**Comment by BBUK** [comment]
Cheers.  I assume you cleared the i2c jumper?  I have one of those Sparkfun boards and I'll have a look this weekend.

**Comment by BBUK** [comment]
@tbrych 
Weird one.  Worked fine in Arch (which I use).  Tried it in Raspbian (which I assume you are using) and had the same error.

Turned out that the initialisation code did not wait long enough for the unsolicited packet.  I have now pushed a fix but you can just increase the usleep in line 821 from 5000 to 10000.

Thanks for the bug report!  Please report back if this is fixed from your end and I'll close the issue.

**Comment by tbrych** [comment]
@BBUK 
Thanks for the help, it worked on my side! 👍

**Comment by BBUK** [comment]
Thanks for the feedback.  Note that I have just changed the fix slightly to make it more robust.
